version: "2.1"

services:
    influxdb:
        image: influxdb:1.2.4
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
        ports:
            - 8083:8083
            - 8086:8086
        privileged: true

    grafana:
        image: grafana/grafana:4.3.2
        volumes:
            - ./grafana/etc:/etc/grafana
            - ./grafana/var/lib:/var/lib/grafana
            - ./grafana/var/lib/plugins:/var/lib/grafana/plugins
            - ./grafana/var/log:/var/log/grafana
        ports:
            - 3000:3000
        privileged: true
